let products=[],productStore=null,fileHandle=null,changed=new Set();
const rows=document.querySelector('#rows'),stats=document.querySelector('#stats'),search=document.querySelector('#search');
const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function useProductData(data){if(Array.isArray(data)){productStore=null;products=data}else{productStore=data;products=Object.entries(data).filter(([,p])=>p&&typeof p==='object').map(([key,p])=>{Object.defineProperty(p,'__key',{value:key,enumerable:false,configurable:true});return p})}changed.clear();render()}
const productKey=p=>p.id||p.code||p.__key;
const serializedProducts=()=>JSON.stringify(productStore||products,null,2);
function render(){const q=normalize(search.value);const filtered=products.filter(p=>!q||normalize([p.code,p.name,p.model,p.brand].join(' ')).includes(q)).slice(0,300);rows.innerHTML='';const frag=document.createDocumentFragment();filtered.forEach(p=>{const tr=document.createElement('tr');if(changed.has(productKey(p)))tr.className='changed';['code','name','brand'].forEach(key=>{const td=document.createElement('td');td.textContent=p[key]||'';tr.append(td)});const td=document.createElement('td'),input=document.createElement('input');input.value=p.price||'';input.placeholder='Liên hệ hoặc 1.250.000₫';input.addEventListener('change',()=>{p.price=input.value.trim()||'Liên hệ';changed.add(productKey(p));render()});td.append(input);tr.append(td);frag.append(tr)});rows.append(frag);stats.textContent=`Hiển thị ${filtered.length}/${products.length} sản phẩm · Đã sửa ${changed.size}`}
async function loadDefault(){const response=await fetch('/data/products.json',{cache:'no-store'});if(!response.ok)throw Error('Không tải được products.json');useProductData(await response.json())}
document.querySelector('#open').onclick=async()=>{if(!window.showOpenFilePicker)return alert('Trình duyệt chưa hỗ trợ. Hãy dùng Chrome/Edge hoặc nút Tải products.json.');[fileHandle]=await showOpenFilePicker({types:[{description:'JSON',accept:{'application/json':['.json']}}]});useProductData(JSON.parse(await(await fileHandle.getFile()).text()))};
document.querySelector('#save').onclick=async()=>{if(!fileHandle)return alert('Hãy bấm Mở products.json trước, hoặc dùng nút Tải products.json.');const writable=await fileHandle.createWritable();await writable.write(serializedProducts());await writable.close();changed.clear();render();alert('Đã lưu products.json.')};
document.querySelector('#download').onclick=()=>{const blob=new Blob([serializedProducts()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='products.json';a.click();URL.revokeObjectURL(a.href)};
search.addEventListener('input',render);loadDefault().catch(error=>stats.textContent=error.message+' — hãy bấm Mở products.json.');