let products=[],productStore=null,projectHandle=null,productsHandle=null,indexHandle=null,changed=new Set();
const rows=document.querySelector('#rows'),stats=document.querySelector('#stats'),search=document.querySelector('#search');
const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function useProductData(data){if(Array.isArray(data)){productStore=null;products=data}else{productStore=data;products=Object.entries(data).filter(([,p])=>p&&typeof p==='object').map(([key,p])=>{Object.defineProperty(p,'__key',{value:key,enumerable:false,configurable:true});return p})}changed.clear();render()}
const productKey=p=>p.id||p.code||p.__key;
const serializedProducts=()=>JSON.stringify(productStore||products,null,2);
const indexFields=['name','code','brand','category','industry','resolution','productType','price','previousPrice','priceUpdatedAt','priceValidUntil','image','thumbnail','link','warranty'];
function serializedIndex(){const result={};if(productStore){Object.entries(productStore).forEach(([id,p])=>{if(!p||typeof p!=='object')return;result[id]={};indexFields.forEach(key=>{if(p[key]!==undefined&&p[key]!==null)result[id][key]=p[key]})})}else{products.forEach((p,i)=>{const id=productKey(p)||String(i);result[id]={};indexFields.forEach(key=>{if(p[key]!==undefined&&p[key]!==null)result[id][key]=p[key]})})}return JSON.stringify(result)}
const displayDate=value=>value?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'Chưa cập nhật';
const localDateTime=value=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
function render(){const q=normalize(search.value);const filtered=products.filter(p=>!q||normalize([p.code,p.name,p.model,p.brand].join(' ')).includes(q)).slice(0,300);rows.innerHTML='';const frag=document.createDocumentFragment();filtered.forEach(p=>{const tr=document.createElement('tr');if(changed.has(productKey(p)))tr.className='changed';['code','name','brand'].forEach(key=>{const td=document.createElement('td');td.textContent=p[key]||'';tr.append(td)});const priceTd=document.createElement('td'),priceInput=document.createElement('input');priceInput.value=p.price||'';priceInput.placeholder='Liên hệ hoặc 1.250.000₫';priceInput.addEventListener('change',()=>{const next=priceInput.value.trim()||'Liên hệ';if(next!==p.price){p.previousPrice=p.price||'Liên hệ';p.price=next;p.priceUpdatedAt=new Date().toISOString();changed.add(productKey(p));render()}});priceTd.append(priceInput);tr.append(priceTd);const updatedTd=document.createElement('td');updatedTd.textContent=displayDate(p.priceUpdatedAt);tr.append(updatedTd);const expiryTd=document.createElement('td'),expiryInput=document.createElement('input');expiryInput.type='datetime-local';expiryInput.value=localDateTime(p.priceValidUntil);expiryInput.addEventListener('change',()=>{p.priceValidUntil=expiryInput.value?new Date(expiryInput.value).toISOString():'';changed.add(productKey(p));render()});expiryTd.append(expiryInput);tr.append(expiryTd);frag.append(tr)});rows.append(frag);stats.textContent=`Hiển thị ${filtered.length}/${products.length} sản phẩm · Đã sửa ${changed.size}`}
async function loadDefault(){const response=await fetch('/data/products.json',{cache:'no-store'});if(!response.ok)throw Error('Không tải được products.json');useProductData(await response.json())}
const handleDb=()=>new Promise((resolve,reject)=>{const request=indexedDB.open('price-manager',1);request.onupgradeneeded=()=>request.result.createObjectStore('handles');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
async function rememberHandle(handle){const db=await handleDb();const tx=db.transaction('handles','readwrite');tx.objectStore('handles').put(handle,'project');return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function recalledHandle(){const db=await handleDb();const tx=db.transaction('handles');const request=tx.objectStore('handles').get('project');return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function useProject(handle){const permission=await handle.queryPermission({mode:'readwrite'});if(permission!=='granted')return false;projectHandle=handle;const dataHandle=await projectHandle.getDirectoryHandle('data');productsHandle=await dataHandle.getFileHandle('products.json');indexHandle=await dataHandle.getFileHandle('products-index.json',{create:true});useProductData(JSON.parse(await(await productsHandle.getFile()).text()));return true}
document.querySelector('#open').onclick=async()=>{if(!window.showDirectoryPicker)return alert('Trình duyệt chưa hỗ trợ. Hãy dùng Chrome/Edge hoặc nút Tải products.json.');const handle=await showDirectoryPicker({mode:'readwrite'});await rememberHandle(handle);if(!await useProject(handle)&&await handle.requestPermission({mode:'readwrite'})==='granted')await useProject(handle)};
document.querySelector('#save').onclick=async()=>{if(!productsHandle||!indexHandle)return alert('Hãy bấm Chọn thư mục dự án và chọn D:\\Du-An29 trước.');const fullWritable=await productsHandle.createWritable();await fullWritable.write(serializedProducts());await fullWritable.close();const indexWritable=await indexHandle.createWritable();await indexWritable.write(serializedIndex());await indexWritable.close();changed.clear();render();alert('Đã đồng bộ products.json và products-index.json.')};
document.querySelector('#download').onclick=()=>{const blob=new Blob([serializedProducts()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='products.json';a.click();URL.revokeObjectURL(a.href)};
search.addEventListener('input',render);(async()=>{try{const saved=await recalledHandle();if(saved&&await useProject(saved))return}catch(error){console.warn(error)}loadDefault().catch(error=>stats.textContent=error.message+' — hãy bấm Chọn thư mục dự án.');})();